enable:
  issues: true
  prs: true

labels:
  "âš™ï¸ Setting":
    include: ['\bSetting\b', '\bsetting\b', '\bSETTING\b']

  "âœ¨ Feature":
    include: ['\bFeat\b', '\bFEAT\b', '\bfeat\b']

  "ğŸŒ Deploy":
    include: ['\bDeploy\b', '\bDEPLOY\b', '\bdeploy\b']

  "ğŸ¨ Design":
    include: ['\bDesign\b', '\bDESIGN\b', '\bdesign\b']

  "ğŸ Fix":
    include: ['\bFix\b', '\bfix\b', '\bFIX\b', '\bBug\b', '\bbug\b', '\bBUG\b']

  "ğŸ“„ Docs":
    include: ['\bDocs\b', '\bDOCS\b', '\bdocs\b']

  "ğŸ“¬ API":
    include: ['\bAPI\b', '\bApi\b', '\bapi\b']

  "ğŸ”¨ Chore":
    include: ['\bCHORE\b', '\bChore\b', '\bchore\b']

  "ğŸ› ï¸ Refactor":
    include: ['\bRefactor\b', '\bREFACTOR\b', '\brefactor\b']

  "ğŸš€ Init":
    include: ['\bInit\b', '\bINIT\b', '\binit\b']